ALTER TABLE tool_configs
  ADD COLUMN visible TINYINT NOT NULL DEFAULT 0 AFTER description,
  ADD COLUMN pinned TINYINT NOT NULL DEFAULT 0 AFTER enabled,
  ADD COLUMN highlighted TINYINT NOT NULL DEFAULT 0 AFTER pinned,
  ADD COLUMN sort_order INT NOT NULL DEFAULT 0 AFTER highlighted;

UPDATE tool_configs
SET visible = 1
WHERE tool_key IN ('KINSHIP_QUERY', 'TRADITIONAL_FESTIVALS', 'SOLAR_TERMS', 'FAMILY_STORIES');
