CREATE TABLE families (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_name VARCHAR(150) NOT NULL,
  family_surname VARCHAR(40) NOT NULL,
  native_place VARCHAR(200) NULL,
  region_code VARCHAR(50) NULL,
  region_text VARCHAR(200) NULL,
  description TEXT NULL,
  avatar_url VARCHAR(500) NULL,
  creator_user_id BIGINT NULL,
  current_founder_member_id BIGINT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
  searchable TINYINT NOT NULL DEFAULT 1,
  public_display_status VARCHAR(40) NOT NULL DEFAULT 'PRIVATE',
  public_contact_name VARCHAR(100) NULL,
  public_contact_phone VARCHAR(30) NULL,
  public_contact_wechat VARCHAR(120) NULL,
  public_contact_note VARCHAR(500) NULL,
  public_contact_visible TINYINT NOT NULL DEFAULT 1,
  tree_mode VARCHAR(40) NOT NULL DEFAULT 'LIST_TREE',
  graph_version BIGINT NOT NULL DEFAULT 1,
  public_applied_at DATETIME NULL,
  public_approved_at DATETIME NULL,
  public_taken_down_at DATETIME NULL,
  disabled_at DATETIME NULL,
  disabled_by_admin_id BIGINT NULL,
  disabled_reason VARCHAR(500) NULL,
  dissolved_at DATETIME NULL,
  restored_at DATETIME NULL,
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_families_name (family_name),
  KEY idx_families_surname (family_surname),
  KEY idx_families_status (status),
  KEY idx_families_searchable (searchable),
  KEY idx_families_public_display_status (public_display_status),
  KEY idx_families_graph_version (graph_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TODO(service): creating a family must also create founder member and FOUNDER link in one transaction.
-- TODO(service): family currently supports only one main family surname.
